theme: jekyll-theme-minimal
title: [The title of your site]
description: [A short description of your site's purpose]
logo: [Location of the logo]
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
